stages:
- name: build
  steps:
  - runScriptConfig:
      image: maven:3.3-jdk-8
      shellScript: mvn clean install
- name: image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-greenhouse:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: index.docker.io
- name: copice
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
