apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    field.cattle.io/creatorId: user-scrn9
  creationTimestamp: 2018-10-08T09:29:45Z
  generation: 2
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-springcloud-m-config
  name: m-config
  namespace: springcloud
  resourceVersion: "2036"
  selfLink: /apis/apps/v1beta2/namespaces/springcloud/deployments/m-config
  uid: b1cf3c8d-cadc-11e8-9997-00163e0ee982
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-springcloud-m-config
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: 2018-10-08T09:33:40Z
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-springcloud-m-config
    spec:
      containers:
      - image: wangyingstudy/config
        imagePullPolicy: Always
        name: m-config
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-10-08T09:33:43Z
    lastUpdateTime: 2018-10-08T09:33:43Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-10-08T09:29:45Z
    lastUpdateTime: 2018-10-08T09:33:43Z
    message: ReplicaSet "m-config-5fb44f697f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
